config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  get 'magic-ball' => 'magic_ball#result'

  get 'guess_my_number' => 'secret_number#guess'
  post 'secret_number_results/:guess' => 'secret_number#result',
    :as => 'secret_number_results'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/magic_ball_controller.rb
class MagicBallController < ApplicationController
  def result
    @magic_answer = generate_random_response
  end

  private
  def generate_random_response
    all_responses = [
      "Maybe. Just maybe.",
      "I suppose so.",
      "Whatever you want."
    ]
    return all_responses.sample
  end
end

app/controllers/secret_number_controller.rb
class SecretNumberController < ApplicationController
  def guess

  end

  def result
    @result = params[:guess].to_i == number
  end

  def number
    return 5
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GamesOnRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/magic_ball/result.html.erb
<h1>Magic 8 Ball</h1>
<hr>
<% if params[:q].present? %>
  <h2>You asked: <%= params[:q] %>?</h2>
  <h2>Magic 8 Ball says: <%= @magic_answer %></h2>
<% else %>
  <%= form_tag("magic-ball", method: :get) %>
  <%= text_field_tag :q, nil, { placeholder: "Enter your question", class: "question_class" } %>
  <%= submit_tag "Ask" %>
<% end %>

app/views/secret_number/guess.html.erb
<h1>Guess my number</h1>

<% 10.times do |i| %>
  <%= link_to("Guess #{i}", secret_number_results_path(guess: i), method: :post) %>
<% end %>

app/views/secret_number/result.html.erb
<%= @result %>

app/views/static_pages/index.html.erb
<h1>Hello, world!</h1>